-- barakoCMS 3.x to 4.0.0 schema migration.
--
-- Generated by `dotnet barakoCMS.dll db-patch <file>` against a database created by 3.21.0, then
-- reviewed by hand. Apply it BEFORE deploying 4.0. Production runs AutoCreate.CreateOnly, which
-- creates missing objects but never alters an existing one, so 4.0 refuses to boot against a 3.x
-- database until this has run. scripts/upgrade-check.sh proves the whole sequence.
--
-- What each statement is, and why it is safe:
--
--   mt_safe_unaccent      Marten 9 schema-qualifies the unaccent call. Function body only.
--                         CASCADE drops nothing else here: no index uses it, and mt_grams_array
--                         calls it from inside a plpgsql body, which Postgres does not track as a
--                         dependency.
--   mt_streams            Drops snapshot and snapshot_version, Marten 8's inline stream-snapshot
--                         columns. barakoCMS never enabled stream snapshots, so both are NULL for
--                         every row by construction rather than by luck. Check before you run it:
--                           select count(snapshot), count(snapshot_version) from mt_streams;
--                         Both must be 0. If they are not, this database used a feature this
--                         project does not, and the columns need keeping rather than dropping.
--   mt_events             Adds bdata bytea NULL, Marten 9's binary event payload column. Additive
--                         and nullable, so existing rows are untouched.
--   mt_quick_append_events Marten 9 changed the signature (bdatas, expected_version) and the body.
--                         Function only, no data.
--   mt_doc_contenttypedefinition
--                         Adds the unique index on a content type's name, per tenant. Uniqueness
--                         used to be a read before the write with nothing behind it, so two
--                         concurrent creates both landed and every lookup by name then resolved the
--                         ambiguity its own way. This is the one statement here that can fail on
--                         real data: run the duplicate check above it first and merge or rename
--                         whatever it finds, because the index cannot be created while a duplicate
--                         exists. Nothing else in 4.0 depends on it, so a database that keeps the
--                         duplicates still boots -- it just keeps the old read-then-write behaviour.
--
-- Rollback is migrations/4.0.0/rollback-to-3.x.sql, which must be applied while 4.0 is stopped.

DROP FUNCTION IF EXISTS public.mt_safe_unaccent(use_unaccent boolean, word text) cascade;
CREATE
OR REPLACE FUNCTION public.mt_safe_unaccent(use_unaccent BOOLEAN, word TEXT)
        RETURNS TEXT
        LANGUAGE plpgsql
        IMMUTABLE STRICT
AS $function$
BEGIN
IF use_unaccent THEN
    RETURN public.unaccent(word);
ELSE
    RETURN word;
END IF;
END;
$function$;


-- The two DROP COLUMNs below are the only destructive statements in this file. The guard turns the
-- "check this first" line in the documentation into a refusal, because a line in documentation is
-- something a hurried operator skips. It raises before either drop runs, so a database that did use
-- stream snapshots stops with its columns intact. Run this file with psql --single-transaction and
-- nothing before it lands either.
DO $guard$
BEGIN
    IF EXISTS (SELECT 1 FROM public.mt_streams
               WHERE snapshot IS NOT NULL OR snapshot_version IS NOT NULL) THEN
        RAISE EXCEPTION
            'mt_streams.snapshot holds data, so this migration will not drop it. barakoCMS never enabled Marten stream snapshots, so this database used a feature this project does not. Ask on the issue tracker before going further.';
    END IF;
END
$guard$;

alter table public.mt_streams drop column snapshot;
alter table public.mt_streams drop column snapshot_version;
alter table public.mt_events add column bdata bytea NULL;
DROP FUNCTION IF EXISTS public.mt_quick_append_events(stream uuid, stream_type character varying, tenantid character varying, event_ids uuid[], event_types character varying[], dotnet_types character varying[], bodies jsonb[]) cascade;

CREATE OR REPLACE FUNCTION public.mt_quick_append_events(stream uuid, stream_type varchar, tenantid varchar, event_ids uuid[], event_types varchar[], dotnet_types varchar[], bodies jsonb[], bdatas bytea[], expected_version integer DEFAULT NULL::integer) RETURNS int[] AS $$
DECLARE
	event_version int;
	stream_is_archived boolean;
	event_type varchar;
	event_id uuid;
	body jsonb;
	index int;
	seq int;
    actual_tenant varchar;
	return_value int[];
BEGIN
    if expected_version IS NOT NULL then
        -- COALESCE turns the NULL we get for a brand-new stream into 0, so a
        -- FetchForWriting against a non-existent stream (which sets
        -- ExpectedVersionOnServer = 0) and a StartStream(id, version: 0) both
        -- land on the new-stream branch instead of mis-firing the guard.
        select version, is_archived into event_version, stream_is_archived from public.mt_streams where id = stream AND tenant_id = tenantid;
        if COALESCE(event_version, 0) != expected_version then
            RAISE EXCEPTION 'Stream version mismatch on ''%'': expected %, actual %', stream, expected_version, COALESCE(event_version, 0) USING ERRCODE = 'MT003';
        end if;
    else
        select version, is_archived into event_version, stream_is_archived from public.mt_streams where id = stream AND tenant_id = tenantid;
    end if;

	if event_version IS NULL then
		event_version = 0;
		insert into public.mt_streams (id, type, version, timestamp, tenant_id) values (stream, stream_type, 0, now(), tenantid);
    else
        if stream_is_archived then
            RAISE EXCEPTION 'Attempted to append event to archived stream with Id ''%''.', stream USING ERRCODE = 'MT001';
        end if;
        if tenantid IS NOT NULL then
            select tenant_id into actual_tenant from public.mt_streams where id = stream AND tenant_id = tenantid;
            if actual_tenant != tenantid then
                RAISE EXCEPTION 'The tenantid does not match the existing stream';
            end if;
        end if;
	end if;

	index := 1;
	-- #5062: array_length('{}', 1) is NULL in PostgreSQL, not 0, so a call with an
	-- empty event array used to return ARRAY[NULL] -- a bigint[] whose only element
	-- is NULL, which Npgsql cannot read into long[] ('Cannot read a non-nullable
	-- collection of elements because the returned array contains nulls'). COALESCE
	-- makes the empty case mean what it says: zero events appended, so the final
	-- version is the stream's current version.
	return_value := ARRAY[event_version + COALESCE(array_length(event_ids, 1), 0)];

	foreach event_id in ARRAY event_ids
	loop
        seq := nextval('public.mt_events_sequence');
		return_value := array_append(return_value, seq);

	    event_version := event_version + 1;
		event_type = event_types[index];
		body = bodies[index];

		-- #4515 / #4578 / Phase 2: bdatas[index] carries the binary payload
		-- for events opted in to binary serialization (NULL otherwise).
		-- bodies[index] is the {} JSON placeholder for those events so the
		-- existing data jsonb NOT NULL constraint stays intact.
		insert into public.mt_events
			(seq_id, id, stream_id, version, data, bdata, type, tenant_id, timestamp, mt_dotnet_type, is_archived)
		values
			(seq, event_id, stream, event_version, body, bdatas[index], event_type, tenantid, (now() at time zone 'utc'), dotnet_types[index], FALSE);

		index := index + 1;
	end loop;

	update public.mt_streams set version = event_version, timestamp = now() where id = stream AND tenant_id = tenantid;

	return return_value;
END
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Content-type name uniqueness, per tenant.
--
-- Run this first. Every row it returns has to be merged or renamed before the
-- CREATE UNIQUE INDEX below will succeed:
--
--   select tenant_id, data ->> 'Name' as name, count(*)
--   from public.mt_doc_contenttypedefinition
--   group by tenant_id, data ->> 'Name'
--   having count(*) > 1;
--
-- The column order matches what Marten generates, so a database that has run
-- this is indistinguishable from a freshly created one.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS mt_doc_contenttypedefinition_uidx_name
    ON public.mt_doc_contenttypedefinition USING btree (((data ->> 'Name'::text)), tenant_id);
