-- barakoCMS 3.x to 4.0.0 schema migration.
--
-- Generated by `dotnet barakoCMS.dll db-patch <file>` against a database created by 3.21.0, then
-- reviewed by hand. Apply it BEFORE deploying 4.0. Production runs AutoCreate.CreateOnly, which
-- creates missing objects but never alters an existing one, so 4.0 refuses to boot against a 3.x
-- database until this has run. scripts/upgrade-check.sh proves the whole sequence.
--
-- What each statement is, and why it is safe:
--
--   mt_safe_unaccent      Marten 9 schema-qualifies the unaccent call. Function body only.
--                         CASCADE drops nothing else here: no index uses it, and mt_grams_array
--                         calls it from inside a plpgsql body, which Postgres does not track as a
--                         dependency.
--   mt_streams            Drops snapshot and snapshot_version, Marten 8's inline stream-snapshot
--                         columns. barakoCMS never enabled stream snapshots, so both are NULL for
--                         every row by construction rather than by luck. Check before you run it:
--                           select count(snapshot), count(snapshot_version) from mt_streams;
--                         Both must be 0. If they are not, this database used a feature this
--                         project does not, and the columns need keeping rather than dropping.
--   mt_events             Adds bdata bytea NULL, Marten 9's binary event payload column. Additive
--                         and nullable, so existing rows are untouched.
--   mt_quick_append_events Marten 9 changed the signature (bdatas, expected_version) and the body.
--                         Function only, no data.
--   mt_doc_pending_registrations
--                         New table. A self-registration that has not confirmed its email address
--                         yet, which 4.0 writes instead of creating a user (#268). Nothing existing
--                         reads or writes it, so creating it moves no data and breaks nothing on
--                         3.x if you never start 4.0.
--   mt_doc_connectors, mt_doc_connector_secrets
--                         New tables. A third party this instance can call, held as configuration
--                         rather than code, and its credentials encrypted under Connectors:Key
--                         (#326). Conjoined multi-tenant, so both carry tenant_id. Empty on
--                         arrival, so creating them moves no data.
--   mt_doc_request_definitions
--                         New table. What to send through a connector, held as configuration
--                         rather than code (#327). Conjoined multi-tenant. Empty on arrival.
--   mt_doc_url_redirects
--                         New table. Old paths that should send a visitor to a new one after a site
--                         rebuild (#112). Conjoined multi-tenant, from-path unique per tenant.
--                         Empty on arrival.
--   mt_doc_query_definitions
--                         New table. A saved way of fetching the rows a payload needs beyond the
--                         entry that triggered it (#328). Conjoined multi-tenant. Empty on arrival.
--   mt_doc_workflow_runs
--                         New table. What a workflow decided to do and how each action went
--                         (#329). Execution moves out of the projection into a background runner,
--                         and this is the queue plus the record. Empty on arrival, so nothing
--                         queued exists until 4.0 starts writing them.
--   mt_doc_email_settings
--                         New table. The email provider credentials an operator entered in the
--                         admin, with the API key encrypted (#343). One row at most. Nothing
--                         existing reads or writes it, so creating it moves no data.
--   mt_doc_contenttypedefinition
--                         Adds the unique index on a content type's name, per tenant. Uniqueness
--                         used to be a read before the write with nothing behind it, so two
--                         concurrent creates both landed and every lookup by name then resolved the
--                         ambiguity its own way. This is the one statement here that can fail on
--                         real data: run the duplicate check above it first and merge or rename
--                         whatever it finds, because the index cannot be created while a duplicate
--                         exists. Nothing else in 4.0 depends on it, so a database that keeps the
--                         duplicates still boots -- it just keeps the old read-then-write behaviour.
--
-- Rollback is migrations/4.0.0/rollback-to-3.x.sql, which must be applied while 4.0 is stopped.

DROP FUNCTION IF EXISTS public.mt_safe_unaccent(use_unaccent boolean, word text) cascade;
CREATE
OR REPLACE FUNCTION public.mt_safe_unaccent(use_unaccent BOOLEAN, word TEXT)
        RETURNS TEXT
        LANGUAGE plpgsql
        IMMUTABLE STRICT
AS $function$
BEGIN
IF use_unaccent THEN
    RETURN public.unaccent(word);
ELSE
    RETURN word;
END IF;
END;
$function$;


-- The two DROP COLUMNs below are the only destructive statements in this file. The guard turns the
-- "check this first" line in the documentation into a refusal, because a line in documentation is
-- something a hurried operator skips. It raises before either drop runs, so a database that did use
-- stream snapshots stops with its columns intact. Run this file with psql --single-transaction and
-- nothing before it lands either.
DO $guard$
BEGIN
    IF EXISTS (SELECT 1 FROM public.mt_streams
               WHERE snapshot IS NOT NULL OR snapshot_version IS NOT NULL) THEN
        RAISE EXCEPTION
            'mt_streams.snapshot holds data, so this migration will not drop it. barakoCMS never enabled Marten stream snapshots, so this database used a feature this project does not. Ask on the issue tracker before going further.';
    END IF;
END
$guard$;

alter table public.mt_streams drop column snapshot;
alter table public.mt_streams drop column snapshot_version;
alter table public.mt_events add column bdata bytea NULL;
DROP FUNCTION IF EXISTS public.mt_quick_append_events(stream uuid, stream_type character varying, tenantid character varying, event_ids uuid[], event_types character varying[], dotnet_types character varying[], bodies jsonb[]) cascade;

CREATE OR REPLACE FUNCTION public.mt_quick_append_events(stream uuid, stream_type varchar, tenantid varchar, event_ids uuid[], event_types varchar[], dotnet_types varchar[], bodies jsonb[], bdatas bytea[], expected_version integer DEFAULT NULL::integer) RETURNS int[] AS $$
DECLARE
	event_version int;
	stream_is_archived boolean;
	event_type varchar;
	event_id uuid;
	body jsonb;
	index int;
	seq int;
    actual_tenant varchar;
	return_value int[];
BEGIN
    if expected_version IS NOT NULL then
        -- COALESCE turns the NULL we get for a brand-new stream into 0, so a
        -- FetchForWriting against a non-existent stream (which sets
        -- ExpectedVersionOnServer = 0) and a StartStream(id, version: 0) both
        -- land on the new-stream branch instead of mis-firing the guard.
        select version, is_archived into event_version, stream_is_archived from public.mt_streams where id = stream AND tenant_id = tenantid;
        if COALESCE(event_version, 0) != expected_version then
            RAISE EXCEPTION 'Stream version mismatch on ''%'': expected %, actual %', stream, expected_version, COALESCE(event_version, 0) USING ERRCODE = 'MT003';
        end if;
    else
        select version, is_archived into event_version, stream_is_archived from public.mt_streams where id = stream AND tenant_id = tenantid;
    end if;

	if event_version IS NULL then
		event_version = 0;
		insert into public.mt_streams (id, type, version, timestamp, tenant_id) values (stream, stream_type, 0, now(), tenantid);
    else
        if stream_is_archived then
            RAISE EXCEPTION 'Attempted to append event to archived stream with Id ''%''.', stream USING ERRCODE = 'MT001';
        end if;
        if tenantid IS NOT NULL then
            select tenant_id into actual_tenant from public.mt_streams where id = stream AND tenant_id = tenantid;
            if actual_tenant != tenantid then
                RAISE EXCEPTION 'The tenantid does not match the existing stream';
            end if;
        end if;
	end if;

	index := 1;
	-- #5062: array_length('{}', 1) is NULL in PostgreSQL, not 0, so a call with an
	-- empty event array used to return ARRAY[NULL] -- a bigint[] whose only element
	-- is NULL, which Npgsql cannot read into long[] ('Cannot read a non-nullable
	-- collection of elements because the returned array contains nulls'). COALESCE
	-- makes the empty case mean what it says: zero events appended, so the final
	-- version is the stream's current version.
	return_value := ARRAY[event_version + COALESCE(array_length(event_ids, 1), 0)];

	foreach event_id in ARRAY event_ids
	loop
        seq := nextval('public.mt_events_sequence');
		return_value := array_append(return_value, seq);

	    event_version := event_version + 1;
		event_type = event_types[index];
		body = bodies[index];

		-- #4515 / #4578 / Phase 2: bdatas[index] carries the binary payload
		-- for events opted in to binary serialization (NULL otherwise).
		-- bodies[index] is the {} JSON placeholder for those events so the
		-- existing data jsonb NOT NULL constraint stays intact.
		insert into public.mt_events
			(seq_id, id, stream_id, version, data, bdata, type, tenant_id, timestamp, mt_dotnet_type, is_archived)
		values
			(seq, event_id, stream, event_version, body, bdatas[index], event_type, tenantid, (now() at time zone 'utc'), dotnet_types[index], FALSE);

		index := index + 1;
	end loop;

	update public.mt_streams set version = event_version, timestamp = now() where id = stream AND tenant_id = tenantid;

	return return_value;
END
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Content-type name uniqueness, per tenant.
--
-- Run this first. Every row it returns has to be merged or renamed before the
-- CREATE UNIQUE INDEX below will succeed:
--
--   select tenant_id, data ->> 'Name' as name, count(*)
--   from public.mt_doc_contenttypedefinition
--   group by tenant_id, data ->> 'Name'
--   having count(*) > 1;
--
-- The column order matches what Marten generates, so a database that has run
-- this is indistinguishable from a freshly created one.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS mt_doc_contenttypedefinition_uidx_name
    ON public.mt_doc_contenttypedefinition USING btree (((data ->> 'Name'::text)), tenant_id);

-- ---------------------------------------------------------------------------
-- Pending self-registrations (#268).
--
-- 4.0 stops writing a user document for a registration nobody confirmed, and
-- writes one of these instead. The column order and the index expressions match
-- what Marten generates, so a database that has run this is indistinguishable
-- from a freshly created one. Empty on arrival, so there is nothing to check
-- first and nothing that can fail on real data.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mt_doc_pending_registrations (
    id                  uuid                        NOT NULL,
    data                jsonb                       NOT NULL,
    mt_last_modified    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
    mt_version          uuid                        NOT NULL DEFAULT (md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar                     NULL,
    CONSTRAINT pkey_mt_doc_pending_registrations_id PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS mt_doc_pending_registrations_idx_email
    ON public.mt_doc_pending_registrations USING btree ((data ->> 'Email'));

CREATE INDEX IF NOT EXISTS mt_doc_pending_registrations_idx_expires_at
    ON public.mt_doc_pending_registrations USING btree ((public.mt_immutable_timestamp(data ->> 'ExpiresAt')));

-- ---------------------------------------------------------------------------
-- Email provider settings (#343).
--
-- 4.0 lets an operator set the email API key in the admin instead of the
-- deployment, and stores it here encrypted. At most one row, so no index earns
-- its place. Empty on arrival: a database that has not had a key entered
-- resolves email from configuration exactly as 3.x did.
-- ---------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- Connectors and their credentials (#326).
--
-- Conjoined multi-tenant, so tenant_id is part of the primary key and of the
-- unique index on the slug: one tenant's "company-jira" is not another's. The
-- secrets are a separate table on purpose, so the object the API returns has
-- nowhere to carry one. Both empty on arrival.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mt_doc_connectors (
    id                  uuid                        NOT NULL,
    data                jsonb                       NOT NULL,
    mt_last_modified    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
    mt_version          uuid                        NOT NULL DEFAULT (md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar                     NULL,
    tenant_id           varchar                     NOT NULL DEFAULT '*DEFAULT*',
    -- Named for the columns it covers, which is what Marten generates for a conjoined document.
    -- pkey_mt_doc_connectors_id would be a schema difference and db-assert refuses the deployment.
    CONSTRAINT pkey_mt_doc_connectors_tenant_id_id PRIMARY KEY (tenant_id, id)
);

-- Per tenant, so one tenant taking "company-jira" does not stop another using it. tenant_id is the
-- second column of the index, which is what TenancyScope.PerTenant generates and what
-- mt_doc_contenttypedefinition_uidx_name above already does.
CREATE UNIQUE INDEX IF NOT EXISTS mt_doc_connectors_uidx_slug
    ON public.mt_doc_connectors USING btree ((data ->> 'Slug'), tenant_id);

CREATE TABLE IF NOT EXISTS public.mt_doc_connector_secrets (
    id                  uuid                        NOT NULL,
    data                jsonb                       NOT NULL,
    mt_last_modified    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
    mt_version          uuid                        NOT NULL DEFAULT (md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar                     NULL,
    tenant_id           varchar                     NOT NULL DEFAULT '*DEFAULT*',
    CONSTRAINT pkey_mt_doc_connector_secrets_tenant_id_id PRIMARY KEY (tenant_id, id)
);

-- Cast to uuid, not left as text. Marten indexes the typed value and a text index is a difference
-- db-assert reports.
CREATE INDEX IF NOT EXISTS mt_doc_connector_secrets_idx_connector_id
    ON public.mt_doc_connector_secrets USING btree ((CAST(data ->> 'ConnectorId' as uuid)));

-- ---------------------------------------------------------------------------
-- Request definitions (#327).
--
-- What to send through a connector. Holds no credential: those are on the
-- connector, encrypted, and are attached to the finished message after this has
-- composed it. Conjoined multi-tenant, slug unique per tenant. Empty on arrival.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mt_doc_request_definitions (
    id                  uuid                        NOT NULL,
    data                jsonb                       NOT NULL,
    mt_last_modified    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
    mt_version          uuid                        NOT NULL DEFAULT (md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar                     NULL,
    tenant_id           varchar                     NOT NULL DEFAULT '*DEFAULT*',
    CONSTRAINT pkey_mt_doc_request_definitions_tenant_id_id PRIMARY KEY (tenant_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS mt_doc_request_definitions_uidx_slug
    ON public.mt_doc_request_definitions USING btree ((data ->> 'Slug'), tenant_id);

-- ---------------------------------------------------------------------------
-- URL redirects (#112).
--
-- One old path and where it should go, so a rebuild does not break every link
-- anyone shared. Conjoined multi-tenant, from-path unique per tenant so one
-- tenant taking "/about" does not stop another having one. Empty on arrival.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mt_doc_url_redirects (
    id                  uuid                        NOT NULL,
    data                jsonb                       NOT NULL,
    mt_last_modified    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
    mt_version          uuid                        NOT NULL DEFAULT (md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar                     NULL,
    tenant_id           varchar                     NOT NULL DEFAULT '*DEFAULT*',
    CONSTRAINT pkey_mt_doc_url_redirects_tenant_id_id PRIMARY KEY (tenant_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS mt_doc_url_redirects_uidx_from_path
    ON public.mt_doc_url_redirects USING btree ((data ->> 'FromPath'), tenant_id);

-- ---------------------------------------------------------------------------
-- Query definitions (#328).
--
-- A content type, typed filters, a sort, a limit and an explicit field
-- projection. Not a query language: nothing here holds an expression. Conjoined
-- multi-tenant, slug unique per tenant. Empty on arrival.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mt_doc_query_definitions (
    id                  uuid                        NOT NULL,
    data                jsonb                       NOT NULL,
    mt_last_modified    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
    mt_version          uuid                        NOT NULL DEFAULT (md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar                     NULL,
    tenant_id           varchar                     NOT NULL DEFAULT '*DEFAULT*',
    CONSTRAINT pkey_mt_doc_query_definitions_tenant_id_id PRIMARY KEY (tenant_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS mt_doc_query_definitions_uidx_slug
    ON public.mt_doc_query_definitions USING btree ((data ->> 'Slug'), tenant_id);

-- ---------------------------------------------------------------------------
-- Workflow runs (#329).
--
-- One row per firing, with an attempt per action inside it. Conjoined
-- multi-tenant. Empty on arrival: a 3.x database has no queued work, and the
-- runs it would have had were executed inline and never recorded.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mt_doc_workflow_runs (
    id                  uuid                        NOT NULL,
    data                jsonb                       NOT NULL,
    mt_last_modified    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
    mt_version          uuid                        NOT NULL DEFAULT (md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar                     NULL,
    tenant_id           varchar                     NOT NULL DEFAULT '*DEFAULT*',
    CONSTRAINT pkey_mt_doc_workflow_runs_tenant_id_id PRIMARY KEY (tenant_id, id)
);

-- Cast to integer, not left as text. Marten's own serializer stores an enum as a number: the
-- JsonStringEnumConverter in ServiceCollectionExtensions is the HTTP serializer only, and the note
-- there says exactly this. mt_doc_contents_idx_status does the same.
CREATE INDEX IF NOT EXISTS mt_doc_workflow_runs_idx_status
    ON public.mt_doc_workflow_runs USING btree ((CAST(data ->> 'Status' as integer)));

CREATE INDEX IF NOT EXISTS mt_doc_workflow_runs_idx_created_at
    ON public.mt_doc_workflow_runs USING btree ((public.mt_immutable_timestamptz(data ->> 'CreatedAt')));

CREATE TABLE IF NOT EXISTS public.mt_doc_email_settings (
    id                  uuid                        NOT NULL,
    data                jsonb                       NOT NULL,
    mt_last_modified    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
    mt_version          uuid                        NOT NULL DEFAULT (md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar                     NULL,
    CONSTRAINT pkey_mt_doc_email_settings_id PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- Content type sourcing policies (#230).
--
-- Whether entries of one content type are event sourced, keyed by the type
-- NAME so that deleting a type and creating it again inherits the answer
-- instead of re-deciding it. Written once per name and never updated or
-- deleted by any code path.
--
-- Empty on arrival, and a name with no row here is not event sourced, which is
-- what every type in a 3.x database is: the document stays the source of truth
-- and events keep being appended for history and audit exactly as before. So
-- creating this table moves no data and changes no behaviour until somebody
-- creates a type asking for event sourcing.
--
-- Multi-tenanted, so tenant_id leads the primary key. The column order and the
-- constraint name match what Marten generates, so a database that has run this
-- is indistinguishable from a freshly created one.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mt_doc_content_type_sourcing_policies (
    tenant_id           varchar                     NOT NULL DEFAULT '*DEFAULT*',
    id                  varchar                     NOT NULL,
    data                jsonb                       NOT NULL,
    mt_last_modified    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
    mt_version          uuid                        NOT NULL DEFAULT (md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar                     NULL,
    CONSTRAINT pkey_mt_doc_content_type_sourcing_policies_tenant_id_id PRIMARY KEY (tenant_id, id)
);

DROP POLICY IF EXISTS marten_tenant_isolation ON public.mt_doc_content_type_sourcing_policies;
ALTER TABLE public.mt_doc_content_type_sourcing_policies NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.mt_doc_content_type_sourcing_policies DISABLE ROW LEVEL SECURITY;

-- Scheduled becomes a real content status (#440, DECISIONS.md D12).
--
-- ContentStatus gained a fourth member, Scheduled = 3, appended rather than
-- inserted so no existing row changes meaning. Marten's serializer has no
-- string enum converter, so these are integers: 0 Draft, 1 Published,
-- 2 Archived, 3 Scheduled.
--
-- A draft carrying a publish time was a draft before this and is Scheduled
-- after it. The condition is exactly what the sweeper used to select on, so
-- this moves the same rows the old code already treated as pending.
--
-- Not destructive and not required. The sweeper accepts both Draft and
-- Scheduled with a publish time, so a database that skips this statement still
-- publishes everything on time; what it loses is the Scheduled filter in the
-- admin, which would show those entries under Draft.
--
-- One thing this cannot do is put the transition in the history. From 4.0 the
-- schedule endpoint appends a ContentStatusChanged next to the ContentScheduled,
-- so a replay reproduces the status. These rows have no such event behind them,
-- so replaying one gives Draft with the date still on it, which the sweeper
-- handles. Entries scheduled after the upgrade do not have that gap.
-- ---------------------------------------------------------------------------
UPDATE public.mt_doc_contents
SET data = jsonb_set(data, '{Status}', '3'::jsonb)
WHERE (data ->> 'Status')::int = 0
  AND data ->> 'ScheduledPublishAt' IS NOT NULL
  AND data -> 'ScheduledPublishAt' <> 'null'::jsonb;
