-- UpdateFieldAction's idempotency marker table (#571 follow-up), core, not a module.
--
-- WHY THIS EXISTS
--
-- The marker used to be a key on the content's own Data. Two things ruled that out. A content edit
-- (Features/Content/Update/Endpoint.cs) replaces Data wholesale, so an editor saving the entry
-- between a workflow's apply and a reclaimed retry silently dropped the mark, and the exact race
-- this exists to close reopened. And nothing filters an unknown Data key out of an authenticated
-- read or an export: SensitivityService only masks fields a schema declares, so
-- GET /api/contents/{id} and BarakoCMS.Portability.ExportEndpoint both handed the mark to anyone
-- who could read the entry. WorkflowFieldApplyMarker.cs carries the fuller version of this.
--
-- INFORMATIONAL ONLY
--
-- This is not required for the upgrade to succeed. Production runs AutoCreate.CreateOnly, which
-- creates a missing object (a brand new table has nothing to conflict with) but never alters an
-- existing one, so Marten adds mt_doc_workflow_field_apply_markers on its own the next time this
-- deploys, whether or not this file was ever run. It is included so an operator can apply it ahead
-- of a deploy and see it in the schema beforehand, rather than the table only being findable by
-- reading the code. Generated by `dotnet barakoCMS.dll db-patch <file>` against an empty database
-- and checked by hand against the actual columns and index name Marten built, the same way the
-- other new tables in 3.x-to-4.0.sql, next to this file, were, rather than typed from memory.
--
--   psql "$DATABASE_URL" -f migrations/4.0.0/workflow-field-apply-marker.sql
--
-- Safe to run twice: both statements are IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS public.mt_doc_workflow_field_apply_markers (
    tenant_id           character varying           DEFAULT '*DEFAULT*'::character varying NOT NULL,
    id                  character varying            NOT NULL,
    data                jsonb                        NOT NULL,
    mt_last_modified    timestamp with time zone     DEFAULT transaction_timestamp(),
    mt_version          uuid                         DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
    mt_dotnet_type      character varying,
    CONSTRAINT pkey_mt_doc_workflow_field_apply_markers_tenant_id_id PRIMARY KEY (tenant_id, id)
);

CREATE INDEX IF NOT EXISTS mt_doc_workflow_field_apply_markers_idx_applied_at
    ON public.mt_doc_workflow_field_apply_markers
    USING btree (public.mt_immutable_timestamptz((data ->> 'AppliedAt'::text)));
