-- UpdateFieldAction's idempotency marker moves off Content.Data onto its own table (#571 follow-up).
--
-- WHY THIS MOVED
--
-- The marker used to be a key on the content's own Data. Two things ruled that out. A content edit
-- (Features/Content/Update/Endpoint.cs) replaces Data wholesale, so an editor saving the entry
-- between a workflow's apply and a reclaimed retry silently dropped the mark, and the exact race
-- this exists to close reopened. And nothing filters an unknown Data key out of an authenticated
-- read or an export: SensitivityService only masks fields a schema declares, so
-- GET /api/contents/{id} and BarakoCMS.Portability.ExportEndpoint both handed the mark to anyone
-- who could read the entry.
--
-- WHAT TO RUN, AND WHEN
--
-- 1. The new table. Nothing here needs it: production runs AutoCreate.CreateOnly, which creates a
--    missing object (a brand new table has nothing to conflict with) but never alters an existing
--    one. So the CREATE below is not required, Marten adds mt_doc_workflow_field_apply_markers on
--    its own the next time this deploys. It is included anyway, generated by
--    `dotnet barakoCMS.dll db-patch <file>` against an empty database and checked by hand against
--    the actual columns and index name Marten built, the same way the other new tables in
--    migrations/4.0.0/3.x-to-4.0.sql are, so an operator can apply it ahead of a deploy rather than
--    finding out at start-up.
--
-- 2. The data cleanup. This one is not optional in the sense the table is: it undoes something the
--    application actually wrote, if it ever ran with the Data-based marker. That version of the fix
--    was never released (no tag was ever cut carrying it), so on most installs this UPDATE matches
--    zero rows. It is still worth running, in case a deployment took it from this branch directly:
--    the keys it removes are permanently dead now that the code reads the marker from the new
--    table, and nothing else strips them.
--
--   psql "$DATABASE_URL" -f migrations/4.2.0/workflow-field-apply-marker.sql
--
-- Safe to run twice: CREATE TABLE/INDEX are IF NOT EXISTS, and the UPDATE only ever matches a row
-- that still carries a stray key, so a second run always reports zero rows touched.

CREATE TABLE IF NOT EXISTS public.mt_doc_workflow_field_apply_markers (
    tenant_id           character varying           DEFAULT '*DEFAULT*'::character varying NOT NULL,
    id                  character varying            NOT NULL,
    data                jsonb                        NOT NULL,
    mt_last_modified    timestamp with time zone     DEFAULT transaction_timestamp(),
    mt_version          uuid                         DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid NOT NULL,
    mt_dotnet_type      character varying,
    CONSTRAINT pkey_mt_doc_workflow_field_apply_markers_tenant_id_id PRIMARY KEY (tenant_id, id)
);

CREATE INDEX IF NOT EXISTS mt_doc_workflow_field_apply_markers_idx_applied_at
    ON public.mt_doc_workflow_field_apply_markers
    USING btree (public.mt_immutable_timestamptz((data ->> 'AppliedAt'::text)));

-- Strips any "__workflow.updateField.applied:*" key the old, Data-based version of this fix wrote,
-- across every tenant partition (mt_doc_contents is one table, conjoined by tenant_id, not one
-- table per tenant, so this single statement already covers all of them). Every other field on the
-- row is kept exactly as it was.
UPDATE public.mt_doc_contents
SET data = (
    SELECT COALESCE(jsonb_object_agg(kv.key, kv.value), '{}'::jsonb)
    FROM jsonb_each(mt_doc_contents.data) AS kv(key, value)
    WHERE kv.key NOT LIKE '__workflow.updateField.applied:%'
)
WHERE EXISTS (
    SELECT 1 FROM jsonb_object_keys(mt_doc_contents.data) k
    WHERE k LIKE '__workflow.updateField.applied:%'
);
